services:
  - type: web
    name: stackit-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 wsgi:app
    envVars:
      - key: SQLALCHEMY_DATABASE_URI
        fromDatabase:
          name: stackit-db
          property: connectionString
      - key: FLASK_ENV
        value: production
  - type: redis
    name: stackit-redis
    plan: free
  - type: database
    name: stackit-db
    databaseType: postgresql